name: restaurant_favourite_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sliding_clipped_nav_bar: ^3.1.0+4
  readmore: ^2.2.0
  lottie: ^2.7.0
  go_router: ^12.1.3
  http:
  provider:
  google_fonts:
  shared_preferences:
  sqflite:
  ndialog: ^4.3.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/developer.json
