// Mocks generated by Mockito 5.4.0 from annotations
// in resto_app/test/provider/restaurant_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:restaurant_favourite_app/src/models/restaurant_list_model.dart'
    as _i2;
import 'restaurant_list_provider_test.dart' as _i6;
import 'dart:async' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRestaurantListResult_0 extends _i1.SmartFake
    implements _i2.RestaurantListModel {
  _FakeRestaurantListResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiServiceTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestaurantServicesTest extends _i1.Mock
    implements _i6.RestaurantServicesTest {
  MockApiServiceTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.RestaurantListModel> listRestaurant() => (super.noSuchMethod(
        Invocation.method(
          #listRestaurant,
          [],
        ),
        returnValue: _i7.Future<_i2.RestaurantListModel>.value(
            _FakeRestaurantListResult_0(
          this,
          Invocation.method(
            #listRestaurant,
            [],
          ),
        )),
      ) as _i7.Future<_i2.RestaurantListModel>);
}
